### ISSUE TITLE
Error when running the demo notebook

### ISSUE THREAD

**Issue by gsnsg** [RonyAbecidan/ManTraNet-pytorch#1]
Hi, When I am trying to run the notebook I am getting the following error
<img width="1080" alt="Screenshot 2021-06-23 at 12 03 06 PM" src="https://user-images.githubusercontent.com/17419092/123047491-fa639300-d41a-11eb-9f3a-6128c95fb80f.png">

**Comment by RonyAbecidan** [comment]
After checking with the author of this issue, the problem was solved relaunching the environment and reconnecting its Google drive with the google colab'. To make things easier next time, I think I am going to propose a collab' associated to the demo notebook soon.
