### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by NavaneethanRajasekaran** [RonyAbecidan/ManTraNet-pytorch#2]
![Screenshot from 2021-09-02 15-08-39](https://user-images.githubusercontent.com/41910620/131821164-c7ab9dff-28e8-4212-b572-62c20e237d35.png)

Device = 'cuda' thrown the above error, adding cpu().detach() helped to resolve it

**Comment by RonyAbecidan** [comment]
Thank you for having reported that error, I accept your pull request ;)
